import type { Question } from "./quiz.types";

export const QUESTION_BANK: Question[] = [
  {
    id: 1,
    questionText: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswerIndex: 2,
    category: "Geography",
  },
  {
    id: 2,
    questionText: "How many continents are there on Earth?",
    options: ["5", "6", "7", "8"],
    correctAnswerIndex: 2,
    category: "Geography",
  },
  {
    id: 3,
    questionText: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Saturn", "Mars"],
    correctAnswerIndex: 1,
    category: "Science",
  },
  {
    id: 4,
    questionText: "What gas do plants absorb from the atmosphere for photosynthesis?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswerIndex: 2,
    category: "Science",
  },
  {
    id: 5,
    questionText: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "NaCl"],
    correctAnswerIndex: 0,
    category: "Science",
  },
  {
    id: 6,
    questionText: "Who wrote the play 'Romeo and Juliet'?",
    options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"],
    correctAnswerIndex: 1,
    category: "Literature",
  },
  {
    id: 7,
    questionText: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correctAnswerIndex: 2,
    category: "Math",
  },
  {
    id: 8,
    questionText: "What is 7 multiplied by 8?",
    options: ["54", "56", "58", "64"],
    correctAnswerIndex: 1,
    category: "Math",
  },
  {
    id: 9,
    questionText: "Which ocean is the largest in the world?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctAnswerIndex: 3,
    category: "Geography",
  },
  {
    id: 10,
    questionText: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"],
    correctAnswerIndex: 1,
    category: "Science",
  },
  {
    id: 11,
    questionText: "In what year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswerIndex: 2,
    category: "History",
  },
  {
    id: 12,
    questionText: "What is the square root of 64?",
    options: ["6", "7", "8", "9"],
    correctAnswerIndex: 2,
    category: "Math",
  },
  {
    id: 13,
    questionText: "Who painted the Mona Lisa?",
    options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
    correctAnswerIndex: 2,
    category: "Art",
  },
  {
    id: 14,
    questionText: "What is the freezing point of water in Celsius?",
    options: ["-10°C", "0°C", "10°C", "32°C"],
    correctAnswerIndex: 1,
    category: "Science",
  },
  {
    id: 15,
    questionText: "Which country is home to the kangaroo?",
    options: ["South Africa", "Australia", "Brazil", "India"],
    correctAnswerIndex: 1,
    category: "Geography",
  },
  {
    id: 16,
    questionText: "What is the longest river in the world?",
    options: ["Amazon River", "Yangtze River", "Nile River", "Mississippi River"],
    correctAnswerIndex: 2,
    category: "Geography",
  },
  {
    id: 17,
    questionText: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correctAnswerIndex: 1,
    category: "Math",
  },
  {
    id: 18,
    questionText: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"],
    correctAnswerIndex: 2,
    category: "History",
  },
  {
    id: 19,
    questionText: "What is the main language spoken in Brazil?",
    options: ["Spanish", "Portuguese", "French", "Italian"],
    correctAnswerIndex: 1,
    category: "Geography",
  },
  {
    id: 20,
    questionText: "What organ in the human body pumps blood?",
    options: ["Lungs", "Liver", "Heart", "Kidney"],
    correctAnswerIndex: 2,
    category: "Science",
  },
  {
    id: 21,
    questionText: "What is 15% of 200?",
    options: ["20", "25", "30", "35"],
    correctAnswerIndex: 2,
    category: "Math",
  },
  {
    id: 22,
    questionText: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    correctAnswerIndex: 1,
    category: "Science",
  },
  {
    id: 23,
    questionText: "Who developed the theory of relativity?",
    options: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Galileo Galilei"],
    correctAnswerIndex: 2,
    category: "Science",
  },
  {
    id: 24,
    questionText: "What is the capital city of Japan?",
    options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
    correctAnswerIndex: 2,
    category: "Geography",
  },
  {
    id: 25,
    questionText: "How many players are on a standard soccer team on the field at once?",
    options: ["9", "10", "11", "12"],
    correctAnswerIndex: 2,
    category: "General Knowledge",
  },
];
